stages:
  - validate
  - merge

validate_code:
  stage: validate
  script:
    - echo "Running tests..."
    - pytest

merge_to_uat:
  stage: merge
  script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git checkout msteamuat-dev-merge-stage
    - git merge msteamdev
    - git push origin msteamuat-dev-merge-stage
  rules:
    - if: $CI_COMMIT_BRANCH == "msteamdev"
=======
  - merge

merge_dev_to_uat:
  stage: merge
  script:
    - echo "Merging dev into uat..."
    - git config user.email "noramin@infopro.com.my"
    - git config user.name "amin"
    - git fetch origin
    - git checkout msteamuat-dev-merge-stage
    - git merge origin/dev --no-ff -m "Auto-merge dev into uat via CI"
    - git push origin msteamuat-dev-merge-stage
  only:
    - dev
  when: manual
